name: Hello GitHub Actions

on: push  # This workflow runs whenever you push code

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Hello, GitHub Actions!"
